# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmoshowcase.info" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Joseph M. O'Connor"
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with my personal portfolio of projects and blogposts" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Designer, Developer, and Blogger.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "tiluser0@gmail.com"
  behance:
  bitbucket:
  dribbble: 
  facebook: "joseph.oconnor.501598"
  flickr:
  github: "tiluser"
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/oconnorjm252/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "tiluser"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-106628939-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]